### PR TITLE
No more need for setting the terminal's window title

### PR DESCRIPTION
**Pull request by ssiegel**
Detect the window id by finding vim's pid (as for tmux), then inspect
its environment to get the value of WINDOWID.

### CODE REVIEW

**Comment by gioele** [comment]
Thank you for the patch. Unfortunately I cannot include it because it does not take into account a use case: when typing `vim` launches gvim, as it is the case when one uses the [vim-veryvisual](https://github.com/gioele/vim-veryvisual) plugin. In that case `WINDOWID` contains the ID of the terminal that launched gvim, not gvim's window.

**Comment by ssiegel** [comment]
I added some logic for gVim, I hope this is acceptable now.

**Comment by gioele** [comment]
I had to do some adjustments to make it work on Ubuntu 14.04. Could you please have a look at the branch `ssiegel-use-procfs` and test if it works for you?

**Comment by ssiegel** [comment]
Vim does not start the server by default if it is running in a terminal, so we need the fallback. After changing that it works as expected :smiley:

**Pull request merged**
